name: Deploy HTML App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6471DC8E1AA544FFA4633EF88B9A024F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1EA1DE4BF9D4BD78F394BB925C53696 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DB8A7E8FFFD4BE1AA90C8D06D267139 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: exp4
          slot-name: Production
          package: 
          
